# Use this file to control the main attributes of the website

# You
name: Manuel Jiménez

# Title for your site as it will appear in google
# e.g. Resume, Curriculum Vitae, Work History
title: CV

# SEO description
description: Manuel Jimenez - Android Developer

# URL of this resume
url: 'http://syhids.github.io'

# URL of your personal website (make same as URL if you don't have one)
personal: 'http://syhids.github.io'

# these should be pretty self-explanatory :-P
email: manuel@yesweapp.eu
twitter: tortill4

# Show this in the footer
copyright: .

# What should the navigation be called?
navigation: navigation

# Google analytics ID: UA-XXXXX-X
analytics: UA-9939917-25

# Jekyll assets gem
assets:
  dirname: assets
  baseurl: /assets/
  css_compressor: yui
  js_compressor: yui
  cachebust: hard
  cache: false
  gzip: nil # Cloudflare will do this
  sources:
    - _assets/javascripts
    - _assets/stylesheets

# Files in this repo that we don't want to go to the web
exclude: [
  'scss',
  '*.rb',
  '*.yml', 
  'vendor', 
  'Gemfile', 
  'Gemfile.lock',
  '*.sh',
  'README.md',
  'LICENSE.md',
]
